forgot to add a done response
Dorumin/Twinkle pull request #38
Opened 2020-10-03 03:26 UTC by LunarTwilight

quick patch for that

2020-10-03 11:15 UTC, Sidemen19 commented
You should probably link to Special:VerifyUser on CC as dev doesn't have the script imported. Tis what Wiki-Bot does for its verification system too.

2020-10-03 12:14 UTC, LunarTwilight commented
Dev might end up importing the script, but if it doesn't, I'll update the link to use CC instead.

2020-10-03 12:22 UTC, puxlit commented on src/plugins/commander/commands/member.js
> +                accept: '*/*'
This was discussed [here](https://discordapp.com/channels/246075715714416641/476452336282107925/761916568782241802), but to summarise, it appears the response content type is `application/hal+json`. When using Got's `.json()` method, the `Accept` request header is implicitly set to `application/json`, which results in a 406 (on cache miss). Thus, setting the `Accept` request header explicitly to either `application/hal+json` or `*/*` remediates this issue.

2020-10-03 12:30 UTC, puxlit requested changes

2020-10-03 12:30 UTC, puxlit commented on src/plugins/commander/commands/member.js
> +            return message.channel.send(`The username and tag in the masthead does not match the username and tag of the message author. Use <https://dev.fandom.com/wiki/Special:VerifyUser/${content}
```suggestion
            return message.channel.send(`The username and tag in the masthead does not match the username and tag of the message author. Use <https://dev.fandom.com/wiki/Special:VerifyUser/${encodeURIComponent(content)}?user=${encodeURIComponent(message.author.username)}&tag=${message.author.discriminator}&c=!member&ch=lobby>.`);
```

2020-10-03 12:56 UTC, puxlit approved these changes
👍

2020-10-08 01:01 UTC, Dorumin approved these changes
yep it's cool all good you're a weeb merging

2020-10-08 01:01 UTC, merged